### ISSUE TITLE
Artisanal + Flow Control for Bob's Logistics causes mod loading error on today's release

### ISSUE THREAD

**Issue by AncalagonX** [kirazy/reskins-library#4]
I am using Angel's + Bob's, along with all the Artisanal reskins. As soon as I updated the Artisanal mods today in Factorio and restarted, it failed to load.

Please let me know if I can provide any better information. You can also ping me on Discord.

![image](https://user-images.githubusercontent.com/37827291/147939513-8d36adb5-009d-4882-a054-ae70d5322a44.png)

**Comment by AncalagonX** [comment]
It also throws an error for [Offshore P.U.M.P.S. and ground water](https://mods.factorio.com/mod/P-U-M-P-S), another mod by @oldskoolmatt

![image](https://user-images.githubusercontent.com/37827291/147942424-8ee28b73-c7cc-4bc6-94fc-a642a2f32503.png)

**Comment by kirazy** [comment]
Oh, this is 'cause of an API change. I've passed it on to Matt.
