### ISSUE TITLE
add a function to return tints per tier

### ISSUE THREAD

**Issue by Yokmp** [kirazy/reskins-library#5]
As the title says. Just a small function to get the used tints per tier. 
This would help to fit mods in the current color sheme; also prevents adding multiple tables for every situation.

**Comment by kirazy** [comment]
How do you mean, precisely?

Currently there's only two tint tables, `reskins.lib.tint_index`, and `reskins.lib.belt_tint_index`, and my understanding is that with Lua it's not defining a table to assign your tint directly e.g. `tint = reskins.lib.tint_index[#]`, it's pointing to it. As these are stored in the global variable `reskins.lib` you can access that during `data` with your mods directly, no need to define a tint table.

A function would be basically `reskins.lib.get_tint(#, return_belt_tint)`, where `#` is tier, and `return_belt_tint` is an optional boolean and then all it would do is

```lua
function reskins.lib.get_tint(tier, return_belt_tint)
   if return_belt_tint
      return reskins.lib.belt_tint_index[tier]
   else
      return reskins.lib.tint_index[tier]
   end
end
```

Which to me is essentially the same? I can write it, if that's what you're asking for. I suppose it could be convenient to be able to fetch a tint with a number and a bool and the same function.

**Comment by Yokmp** [comment]
Oh, i wasn't aware of that table. I tried it now but it seems like it indexes its tints by 0 instead of 1
Is this intended? I have to check for the mod and shift the table by 1.
A table indexed by 1 would be nice. Also getting belt and machine tints separately would be handy i think (though i just tint machines in my mod). I don't think a function returning a single tint would be handy a if someone uses tints for tiers they probably already have a table with tints so they can like switch them around in a single line.

**Comment by kirazy** [comment]
This is intended. They are indexed by tier, and there is a tier 0.
